---
sudo: required
language: python
python:
  - "3.6"

env:
  global:
    - ANSIBLE_HOST_KEY_CHECKING="False"

# Install python-pip
addons:
  apt:
    packages:
      - python-pip

install:
  - pip install tox ansible yamllint

  # Check ansible version
  - ansible --version

script:
  # Run sytax checks and linters
  - tox

# Galaxy cannot handle the fact that role is in subdirectory
# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
