---
- name: Install packages for OpenStack appliance
  yum:
    name: "{{ item }}"
    state: "{{ v2v_yum_check }}"
  with_items:
    - python2-openstackclient
    - virtio-win
    - python-six

- name: Look for SSH key
  stat:
    path: "~root/.ssh/id_rsa"
  ignore_errors: "yes"
  register: stat_ssh_key

- name: Create SSH key
  command: ssh-keygen -b 4096 -t rsa -f ~root/.ssh/id_rsa -N ''
  when: not stat_ssh_key.stat.exists
