---
- name: Look for SSH key
  stat:
    path: "/var/lib/vdsm/.ssh/id_rsa"
  ignore_errors: "yes"
  register: stat_ssh_key

- name: Create .ssh directory
  file:
    path: /var/lib/vdsm/.ssh
    owner: vdsm
    group: kvm
    mode: 0700
    state: present
  become: true
  become_user: vdsm
  when: not stat_ssh_key.stat.exists

- name: Create SSH key
  command: ssh-keygen -b 4096 -t rsa -f /var/lib/vdsm/.ssh/id_rsa -N ''
  become: true
  become_user: vdsm
  when: not stat_ssh_key.stat.exists

- name: Install oVirt SDK
  yum:
    state: "{{ v2v_yum_check }}"
    name: python-ovirt-engine-sdk4
