---
- name: Install packages for OpenStack appliance
  yum:
    name: "{{ item }}"
    state: "{{ v2v_yum_check }}"
  with_items:
    - python2-openstackclient
    - virtio-win
    - python-six

- name: Look for SSH key
  stat:
    path: "~root/.ssh/id_rsa"
  ignore_errors: "yes"
  register: stat_ssh_key

- name: Create SSH key
  command: ssh-keygen -b 4096 -t rsa -f ~root/.ssh/id_rsa -N ''
  when: not stat_ssh_key.stat.exists

- name: Configuring cron job for log cleanup
  copy:
    dest: /etc/cron.daily/virt-v2-logs
    owner: root
    group: root
    mode: 0755
    content: |
      #!/bin/sh
      errors=0
      if [ -d /var/log/virt-v2v ] ; then
          /usr/bin/find /var/log/virt-v2v -type f -mtime +30 -exec /bin/rm -f '{}' \;
          EXITVALUE=$?
          if [ $EXITVALUE != 0 ]; then
              /usr/bin/logger -t virt-v2v-logs "ALERT clean of old import log files exited abnormally with [$EXITVALUE]"
              errors=$((errors+1))
          fi
      fi
      if [ $errors -ne 0 ]; then
          exit 1
      fi
