---
- set_fact:
    ssh_config_path: "/var/lib/vdsm/.ssh"
    ssh_config_owner: "vdsm"
  when:
    - "v2v_host_type == 'rhv'"

- set_fact:
    ssh_config_path: "/root/.ssh"
    ssh_config_owner: "root"
  when:
    - "v2v_host_type == 'openstack'"

- include_tasks: "install-transport-ssh-user-key.yml"

- include_tasks: "install-transport-ssh-vmware-host-key-from-inventory.yml"
  when:
    - "'vmware_hosts' in groups"
    - "hostvars[vmware_host]['conversion_ssh_private_key'] is defined"
  loop: "{{ groups['vmware_hosts'] }}"
  loop_control:
    loop_var: vmware_host

- include_tasks: "install-transport-ssh-vmware-host-key-from-variable.yml"
  when:
    - "vmware_hosts is defined"
    - "vmware_host.name is defined"
    - "vmware_host.conversion_ssh_private_key is defined"
  loop: "{{ vmware_hosts }}"
  loop_control:
    loop_var: vmware_host
