---
- name: Download Makefile file
  get_url:
    url: "http://git.annexia.org/?p=nbdkit-plugin-vddk.git;a=blob_plain;f=Makefile;hb=HEAD"
    dest: "{{ v2v_build_dir }}/Makefile"
    mode: 0400

- name: Download spec file
  get_url:
    url: "http://git.annexia.org/?p=nbdkit-plugin-vddk.git;a=blob_plain;f=nbdkit-plugin-vddk.spec;hb=HEAD"
    dest: "{{ v2v_build_dir }}/nbdkit-plugin-vddk.spec"
    mode: 0400

- name: Download nbdkit source
  command: make check-source
  args:
    chdir: "{{ v2v_build_dir }}"
    creates: x86_64
