---
- name: Look for existing SSH private key file
  stat:
    path: "{{ ssh_config_path }}/id_rsa"
  ignore_errors: "yes"
  register: stat_ssh_key

- block:
    - fail:
        msg: "No file named '{{ ssh_config_path }}/id_rsa' found and no 'v2v_ssh_private_key' variable set"
      when:
        - "v2v_ssh_private_key is not defined"

    - name: Create the SSH private key file
      copy:
        dest: "{{ ssh_config_path }}/id_rsa"
        content: "{{ v2v_ssh_private_key }}"
        owner: "{{ ssh_config_owner }}"
        mode: 0600

  when: not stat_ssh_key.stat.exists
