---
- set_fact:
    ssh_config_path: "/var/lib/vdsm/.ssh"
    ssh_config_owner: "vdsm"
  when:
    - "v2v_host_type == 'rhv'"

- set_fact:
    ssh_config_path: "/root/.ssh"
    ssh_config_owner: "root"
  when:
    - "v2v_host_type == 'openstack'"

- include_tasks: "install-transport-ssh-private-key.yml"
