---
- name: Delete SSH private key file for VMware host
  file:
    path: "{{ ssh_config_path }}/{{ vmware_host }}"
    state: absent

- name: Remove SSH config entry for VMware host
  blockinfile:
    path: "{{ ssh_config_path }}/config"
    block: |
      Host {{ vmware_host }}
        User {{ hostvars[vmware_host]['conversion_ssh_username'] | default('root') }}
        IdentityFile {{ ssh_config_path }}/{{ vmware_host }}
    state: absent
