---
galaxy_info:
  author: Fabien Dupont, Tomáš Golembiovský
  description: Setup oVirt host as conversion host for ManageIQ
  company: Red Hat, Inc.
  license: Apache License 2.0
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags: [ovirt, rhv, rhev, virtualization]
